name: ci

on:
  push:
    branches:
      - v3
  pull_request:
    branches:
      - v3

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint

      - name: Typecheck
        run: yarn run typecheck
